### ISSUE TITLE
Better step by step installation

### ISSUE THREAD

**Issue by julesmoretti** [revolunet/sublimetext-google-apps-scripts#13]
Hello there, it would be great if you had a better step by step instruction on how to get your plugin up and running.

So for example how do I export and import a google script? How do I install it on my machine? using package editor?

Thank you for your help.

**Comment by revolunet** [comment]
Well it only worked on sublime text 2 and i dont use it anymore...

Btw, the steps were : 
 - install from ST2 + package manager
 - use "browse projects" in the palette
 - the plugin ask you a oauth token (in the bottom console) 

The you can browser and edit the scripts directly

**Comment by julesmoretti** [comment]
Thank you @revolunet - just by curiosity, you no longer use it just because you dont use Google script anymore or did you move to a better workflow?

**Comment by revolunet** [comment]
Hi,

I found the google apps script developer experience quite painful so i dont use it much anymore

This may help : https://github.com/danthareja/node-google-apps-script
